apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: thesis
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rabbitmq.service.port | int }}
            - containerPort: {{ .Values.rabbitmq.managementPort | int }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: thesis
spec:
  ports:
    - port: {{ .Values.rabbitmq.service.port | int }}
      targetPort: {{ .Values.rabbitmq.service.port | int }}
      name: amqp
    - port: {{ .Values.rabbitmq.managementPort | int }}
      targetPort: {{ .Values.rabbitmq.managementPort | int }}
      name: management
  selector:
    app: rabbitmq
