apiVersion: v1
kind: Service
metadata:
  namespace: thesis
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: {{ .Values.rabbitmq.service.port }}
      targetPort: {{ .Values.rabbitmq.service.port }}
      name: amqp
    - port: {{ .Values.rabbitmq.managementPort }}
      targetPort: {{ .Values.rabbitmq.managementPort }}
      name: management
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
      name: mongo
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: worker-manager
  labels:
    app: worker-manager
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.workerManager.service.port }}
  selector:
    app: worker-manager
---
apiVersion: v1
kind: Service
metadata:
  namespace: thesis
  name: result-analyzer
  labels:
    app: result-analyzer
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.resultAnalyzer.service.port }}
  selector:
    app: result-analyzer
