apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
  labels:
    {{- include "app-chart.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
  namespace: "{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
