apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-manager
  labels:
    app: worker-manager
spec:
  replicas: {{ .Values.workerManager.replicaCount }}
  selector:
    matchLabels:
      app: worker-manager
  template:
    metadata:
      labels:
        app: worker-manager
    spec:
      serviceAccountName: "{{ .Values.serviceAccount.name | default .Chart.Name }}"
      containers:
        - name: worker-manager
          image: "{{ .Values.workerManager.image.repository }}:{{ .Values.workerManager.image.tag }}"
          imagePullPolicy: {{ .Values.workerManager.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.workerManager.service.port }}
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:{{ .Values.rabbitmq.service.port }}"
            - name: MONGODB_URL
              value: "mongodb://mongodb:{{ .Values.mongodb.service.port }}/testresults"
            - name: ENVIRONMENT
              value: "{{ .Values.config.environment }}"
            - name: API_PREFIX
              value: "{{ .Values.config.apiPrefix }}"
            - name: API_VERSION
              value: "{{ .Values.config.apiVersion }}"
            - name: API_HOST
              value: "{{ .Values.config.apiHost }}"
            - name: APP_HOST
              value: "{{ .Values.config.appHost }}"
            - name: APP_PORT
              value: "{{ .Values.config.appPort }}"
            - name: LOGS_PATH
              value: "{{ .Values.config.logsPath }}"
            - name: COOKIE_SECRET
              value: "{{ .Values.config.cookieSecret }}"
---
apiVersion: v1
kind: Service
metadata:
  name: worker-manager
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.workerManager.service.port }}
  selector:
    app: worker-manager
